

# This file was *autogenerated* from the file cpu_v_gpu.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8); _sage_const_32003 = Integer(32003)
execfile('f5_2.py');

var_count = _sage_const_8 
P = PolynomialRing(GF(_sage_const_32003 ),var_count,'x');
I = sage.rings.ideal.Katsura(P).homogenize();

print(P);
print('CPU\n=======================================================================')
gb = f5_2(I, use_cpu = True); f5_2.print_stats();

print(P);
print('GPU:\n=======================================================================')
gb = f5_2(I); f5_2.print_stats();

