

# This file was *autogenerated* from the file test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_32003 = Integer(32003); _sage_const_4 = Integer(4)
execfile('f5_2.py');
P = PolynomialRing(GF(_sage_const_32003 ),_sage_const_4 ,'x');
print(P);
I = sage.rings.ideal.Cyclic(P).homogenize();
print('=======================================================================')
gb = f5_2(I); f5_2.print_stats();

