

# This file was *autogenerated* from the file test2.sage
from sage.all_cmdline import *   # import sage library

_sage_const_8 = Integer(8)
execfile('f5_2.py');
P = PolynomialRing(QQ,_sage_const_8 ,'x');
print(P);
I = sage.rings.ideal.Katsura(P).homogenize();
print('=======================================================================')
gb = f5_2(I); f5_2.print_stats();

